$ANSIBLE_VAULT;1.1;AES256
61393532626461333434393735313062393030373536343536333737383564326665356365613166
6262373532336332393362623031336664376137323434650a616637623234653863633435613936
38316130633266373538663137306639313534366265373939333763643464616665666234333638
3735333637316131610a666135666366303562393334343362663939633738333331393037386635
35666166313762643131363634313637336337333932343031346637313962666263373263666632
35383434393566313734323366616137353463373731373332303537343864356234343335383664
36376338333266383361643061643066633133363733346636313332653364326235383331313239
38383265353130313839636135643466613039346230373239636534306361333639646261656261
65353938663838353234323138623138643830303038313231386462343534386666363130636435
64633734373763613034333162613333383536633566323530623666613765383733373933303736
37623430376135366566633432373331326634616539643762373238663066613337336266383531
38363166356361373831626636666138336232623438363834623435623938376363613062613239
35353236663436373430316563363935336330323438623739366236366566666263376436633966
3639353761626664653239353163666337313833623737333362
